### ISSUE TITLE
Invalid argument(s): match is not a SpatialGuess

### ISSUE THREAD

**Issue by richardloxley** [inway/dart_zxcvbn#18]
I'm seeing uncaught exceptions for certain passwords.

e.g.

`final result = zxcvbn('qwe');`

or

`final result = zxcvbn('zxc');`

These throw `ArgumentError('match is not a SpatialGuess')` from `packages/dart_zxcvbn/lib/src/matcher/spatial.dart` (line 223).

I don't know enough about the structure of the code to work out what's going on.  Any suggestions?  For now I'll probably catch the exceptions, and assume such an exception means a weak password has been identified, but it would be good to figure out the problem and fix it.

**Comment by SPodjasek** [comment]
This should be fixed in `dart_zxcvbn` version `0.1.0+5`

**Comment by richardloxley** [comment]
Thank you for the amazingly quick fix!  I've confirmed the new version fixes the problem I saw.  Great package - thanks.
